/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sistemas;

public class App {
    
    // Diseñe un algoritmo para saludar al usuario: Hola usuario. El nombre del usuario es ingresado por teclado
    public static String saludarUsuario(String nombre) {
        try {
            // Lógica interna
            return "Hola " + nombre;

        } catch (Exception e) {
            return "Error: " + e.getMessage();
        }
        
    }

    // Diseñe un algoritmo que lea por teclado una velocidad en Km/seg y la convierta a metros/seg y a metros/hora
    // retorne el valor en formato string (metrosPorSeg + "|" + metrosPorHora)
    public static String convertirVelocidad(double kmPorSeg) {
        try {
            // Lógica interna

            //Inicialización de las variables en cero
            double metrosPorSeg = 0;
            double metrosPorHora = 0;

            //Realización de calculos
            metrosPorSeg = kmPorSeg * 1000;
            metrosPorHora = metrosPorSeg * 3600;

            //Resultados
            return (int)metrosPorSeg + "|" + (int)metrosPorHora;
        } catch (Exception e) {
            return "0|0";
        }
        
    }

    // Solicitar al usuario ingresar una cantidad expresada en cc (centímetros cúbicos) y devolver su cantidad en litros
    public static int convertirCcALitros(double cc) {
        try{
            //Lógica interna
            //Inicialización de las variables
            double cantidadEnLitros = 0;

            //Procesos
            cantidadEnLitros = cc / 1000;

            //Resultados
            return (int) cantidadEnLitros;

        } catch (Exception e) {
            return -1;
        }
    }
    //Solicitar al usuario ingresar una cantidad en dólares y convertirla a pesos según la TRM del día
    public static int convertirDolaresAPesos(double dolares, double trm) {
        try {
            // Lógica interna
            //Inicializacion de las variables
            double pesos = 0;

            //Procesos
            pesos = dolares * trm;

            //Resultado
            return (int) pesos;            

        } catch (Exception e) {
            return -1;
        }
        
    }

    // Solicitar al usuario ingresar la temperatura en grados centígrados y convertirla en grados Fahrenheit (averiguar la fórmula) F = 32 + ( 9 * C / 5)
    public static int convertirCelsiusAFahrenheit(double celsius) {
        try {
            // Lógica interna
            //Inicializacion de variables
            double gradosFahrenheit = 0;

            //Procesos
            gradosFahrenheit = 32 + (9 * celsius / 5);

            //Resultados
            return (int)gradosFahrenheit; 
        
        } catch (Exception e) {
            return -1;
        }
       
    }

    // Solicitar al usuario ingresar Nro de Días nro de horas nro de minutos y nro segundos y convertir todo a segundos.
    public static int convertirATotalSegundos(int dias, int horas, int minutos, int segundos) {
        try {
            // Lógica interna
            //Inicializacion
            double totalSegundos = 0;

            //Proceso
            totalSegundos = (dias * 86400) + (horas * 3600) + (minutos * 60) + (segundos * 1);

            //Resultado
            return (int) totalSegundos;
        } catch (Exception e) {
            return -1;
        }
        
    }

    // Un usuario tiene un sistema de báscula para pesar camiones, dado el peso de un camión debe sacar el peso neto de la carga en kilos y toneladas
    // retorne el valor en formato string (pesoEnKg + "|" + pesoEnToneladas)
    public static String calcularPesoNeto(double peso) {
        try {
            // Lógica interna
            //Inicializacion
            double pesoEnKg = 0;
            double pesoEnToneladas = 0;

            //Proceso
            pesoEnKg = peso / 1000;
            pesoEnToneladas = peso / 1000000;

            //Resultado
            return (int)pesoEnKg + "|" + (int)pesoEnToneladas;

        } catch (Exception e) {
            return "0|0";
        }
        
    }

    // Diseñe un algoritmo que calcule el tiempo necesario para alcanzar un destino dado por el usuario quien además ingresará la velocidad promedio en kilómetros/hora y la distancia en kilómetros
    public static int calcularTiempoViaje(double distancia, double velocidadKilometros, double velocidadHora) {
        try {
            // Lógica interna

            //Control de errores
            if (distancia == 0 || velocidadKilometros == 0 || velocidadHora == 0) {
                return -1;
            }
            //Declaracion e Inicializacion
            double kilometrosXHora = velocidadKilometros / velocidadHora;
            double tiempoNecesario = 0;

            //Proceso
            tiempoNecesario = distancia / kilometrosXHora;

            //Resultado
            return (int)tiempoNecesario;

        } catch (Exception e) {
            return -1;
        }
      
    }

    // Un avión necesita cargar combustible para cubrir sus rutas programadas en el día. Cada 0.2 toneladas de combustible puede recorrer 60.8 Km en velocidad de crucero. En el despegue el avión consume 1.2 toneladas de combustible y en el aterrizaje consume 0.4 toneladas. El piloto desea un algoritmo que ingresando 4 rutas y el kilometraje de cada ruta obtenga la cantidad de combustible que debe tanquear en el avión.
    public static int calcularCombustible(double ruta1, double ruta2, double ruta3, double ruta4) {
        try {
            // Lógica interna

            //Declaracion e Inicializacion
            double despegue = 1.2;
            double aterrizaje = 0.4;
            double toneladasPorKilometro = 0.2/60.8;
            double toneladasRuta1 = 0;
            double toneladasRuta2 = 0;
            double toneladasRuta3 = 0;
            double toneladasRuta4 = 0;
            double toneladasRequeridas = 0;

            //Procesos
            toneladasRuta1 = (toneladasPorKilometro * ruta1) + despegue + aterrizaje;
            toneladasRuta2 = (toneladasPorKilometro * ruta2) + despegue + aterrizaje;
            toneladasRuta3 = (toneladasPorKilometro * ruta3) + despegue + aterrizaje;
            toneladasRuta4 = (toneladasPorKilometro * ruta4) + despegue + aterrizaje;

            toneladasRequeridas = toneladasRuta1 + toneladasRuta2 + toneladasRuta3 + toneladasRuta4;

            //Resultados
            return (int)toneladasRequeridas;

        } catch (Exception e) {
            return -1;
        }
    }

    // Diseñar un algoritmo que calcule el peso neto en la luna de un peso terrestre ingresado por teclado. La gravedad de la Luna es de alrededor del 17% más que la de la tierra
    public static int calcularPesoLunar(double pesoTierra) {
        try {
            // Lógica interna

            //Declaracion e Inicializacion
            double pesoLunar = 0;
            double gravedadDeLaLuna = 1.17;

            //Proceso
            pesoLunar = pesoTierra * gravedadDeLaLuna ;

            //Resultado
            return(int) pesoLunar;
        } catch (Exception e) {
            return -1;
        }
        
    }

    // Diseñar un algoritmo que calcule el saldo que debe haber en una taquilla de un banco. El cajero deberá ingresar la base el total de recaudos y el total de retiros
    public static int calcularSaldoTaquilla(double base, double ingresos, double retiros) {
        try {
            // Lógica interna

            //Inicializacion
            double saldo = 0;

            //Proceso
            saldo = base + ingresos - retiros;

            //Resultado
            return (int)saldo;

        } catch (Exception e) {
            return -1;
        }
       
    }

    // Diseñe un algoritmo para calcular la propina en un restaurante(10%) el impuesto al consumo (8%) y el valor final que deberá pagar ingresando el valor de la comida.
    // retorne el valor en formato string (propina + "|" + impuesto + "|" + total)
    public static String calcularCuentaRestaurante(double costoComida) {
        try {
            // Lógica interna

            //Inicializacion
            double propina = 0;
            double impuesto = 0;
            double total = 0;

            //Procesos
            propina = costoComida * 0.10;

            impuesto = costoComida * 0.08;

            total = costoComida + propina + impuesto;

            //Resultado
            return (int) propina + "|" + (int) impuesto + "|" + (int) total;

            //Control de errores
        } catch (Exception e) {
            return -1 + "|" + -1 + "|" + -1;
        }
        
    }

    // Diseñar un algoritmo que obtenga los puntos finales de un equipo de fútbol (puntuación según lineamientos de Fifa) a partir de los datos ingresados por teclado: Número de partidos ganados número de partidos perdidos número de partidos empatados.
    public static int calcularPuntosFutbol(int ganados, int perdidos, int empatados) {
        try {
            // Lógica interna

            //Inicializacion, aqui no se declaran los partidos perdidos, porque no serán de utilidad
            double puntosGanados = 0;
            double puntosFinales = 0;

            //Procesos, aqui los partidos empatados se toman directamente por su equivalencia a un punto, sin necesidad de hacer operaciones con el dato ingresado
            puntosGanados = ganados * 3;
            puntosFinales = puntosGanados + empatados;

            //Resultado
            return (int)puntosFinales;

        } catch (Exception e) {
            return -1;
        }
        
    }

    // Elaborar un algoritmo que dadas todas las 5 notas y los 5 porcentajes para una materia calcule la nota final.
    public static int calcularNotaFinal(double nota1, double nota2, double nota3, double nota4, double nota5,
                                        double porcentaje1, double porcentaje2, double porcentaje3, double porcentaje4, double porcentaje5) {
        try {
            // Lógica interna

            //Control de errores
            if (porcentaje1 == 0 || porcentaje2 == 0 || porcentaje3 == 0 || porcentaje4 == 0 || porcentaje5 ==0){
                return -1;
            }
            
            //Inicializacion
            double primeraNota = 0;
            double segundaNota = 0;
            double terceraNota = 0;
            double cuartaNota = 0;
            double quintaNota = 0;
            double notaFinal = 0;

            //Procesos
            primeraNota = nota1 * porcentaje1;
            segundaNota = nota2 * porcentaje2;
            terceraNota = nota3 * porcentaje3;
            cuartaNota = nota4 * porcentaje4;
            quintaNota = nota5 * porcentaje5;

            notaFinal = primeraNota + segundaNota + terceraNota + cuartaNota + quintaNota;
           
            //Resultado
            return (int)notaFinal;

        } catch (Exception e) {
          return -1;
        }
    }

    // Elaborar un algoritmo que dados los 5 porcentajes de una materia y las 4 primeras notas calcule cuánto tiene que sacar para ganar si el puntaje mínimo es 3.
    public static int calcularNotaNecesaria(double porcentaje1, double porcentaje2, double porcentaje3, double porcentaje4, double porcentaje5, double nota1, double nota2, double nota3, double nota4) {
        try {
            // Lógica interna

            //Control de errores
            if (porcentaje1 == 0 || porcentaje2 == 0 || porcentaje3 == 0 || porcentaje4 == 0){
                return -1;
            }
            
            //  Inicializacion
            double primeraNotaFinal = 0;
            double segundaNotaFinal = 0;
            double terceraNotaFinal = 0;
            double cuartaNotaFinal = 0;
            double quintaNotaFinal = 0;

            //Procesos
            primeraNotaFinal = nota1 * porcentaje1;
            segundaNotaFinal = nota2 * porcentaje2;
            terceraNotaFinal = nota3 * porcentaje3;
            cuartaNotaFinal = nota4 * porcentaje4;

            quintaNotaFinal = 3-(primeraNotaFinal + segundaNotaFinal + terceraNotaFinal + cuartaNotaFinal);
            
            //Resultados
            if(quintaNotaFinal <= 0){
                return -1;
            }
            return (int)quintaNotaFinal;

        }catch (Exception e) {
            return -1;
        }
    
    }

    // Se requiere un algoritmo para calcular el salario a pagar a un trabajador con los siguientes datos ingresados por teclado: cantidad de horas normales laboradas cantidad de horas extras diurnas laboradas cantidad de horas extras nocturnas laboradas valor de la hora normal. El valor de las horas extras diurnas tienen un recargo adicional del 15% sobre la hora normal. El valor de las horas extras nocturnas tienen un recargo adicional del 35% sobre la hora normal.
    public static int calcularSalario(int horasNormales, int horasExtrasDiurnas, int horasExtrasNocturnas, double valorHoraNormal) {
        try {
            // Lógica interna

            //Inicializacion
            double valorHorasExtrasDiurnas = 0;
            double valorHorasExtrasNocturnas = 0;
            double valorTotalHorasExtrasDiurnas = 0;
            double valorTotalHorasExtrasNocturnas = 0;
            double valorTotalHorasNormales = 0;
            double salario = 0;

            //Procesos
            valorHorasExtrasDiurnas = valorHoraNormal +(valorHoraNormal * 0.15);
            valorHorasExtrasNocturnas = valorHoraNormal +(valorHoraNormal * 0.35);

            valorTotalHorasExtrasDiurnas = horasExtrasDiurnas * valorHorasExtrasDiurnas;
            valorTotalHorasExtrasNocturnas = horasExtrasNocturnas * valorHorasExtrasNocturnas;
            valorTotalHorasNormales = horasNormales * valorHoraNormal;

            salario = (int)valorTotalHorasNormales + (int)valorTotalHorasExtrasDiurnas + (int)valorTotalHorasExtrasNocturnas;
           
            //Resultado con control de errores
            if( salario == 0){return -1;
            }
            else {
            return (int)salario;
            }


        } catch (Exception e) {
            return -1;
        }
    }

    // Diseñe un algoritmo que calcule el área de un triángulo rectángulo.
    public static int calcularAreaTriangulo(double base, double altura) {
        try {
            // Lógica interna

            //Inicializacion
            double area = 0;

            //Proceso
            area = (base * altura)/2;

            //Resultado
            return (int)area;

        } catch (Exception e) {
            return -1;
        }

    }

    // Diseñe un algoritmo que calcule el perímetro de un cuadrado.
    public static int calcularPerimetroCuadrado(double lado) {
        try {
            // Lógica interna

            //Inicializacion
            double perimetro = 0;

            //Proceso
            perimetro = lado*4;

             //Resutado
            return (int)perimetro;

        } catch (Exception e) {
            return -1;
        }
    }

    // Diseñe un algoritmo que calcule el volumen de un cilindro.
    public static int calcularVolumenCilindro(double radio, double altura) {
        try {
            // Lógica interna

            //Declaracion e Inicializacion
            double radioAlCuadrado = radio * radio;
            double pi = Math.PI;
            double volumen = 0;

            //Proceso
            volumen = radioAlCuadrado * pi * altura;

            //Resultado
            return (int)volumen;

        } catch (Exception e) {
            return -1;
        }
        
    }

    // Diseñe un algoritmo que calcule el área del círculo. El radio se pide por teclado.
    public static int calcularAreaCirculo(double radio) {
        try {
            // Lógica interna

            //Inicializacion 
            double area = 0;
            double pi = Math.PI;
            double radioAla2 = radio * radio;

            area = pi * radioAla2;

            return (int)area;
        } catch (Exception e) {
            return -1;
        }
    }

    public static void main(String[] args) {
      
    }
}
